% Author:
% Date: 11-Jul-17

%eastbound([c(1,ellipse,long,none,l(rectangle,2)),c(2,rectangle,long,flat,l(circle,3)),c(3,rectangle,long,none,l(triangle,2)),c(4,hexagon,short,flat,l(triangle,1))])


feature(T) :- arg(1,T,L), examine(L).

examine(([])).
examine((T)):-
                   open('trains_feature_csv.txt',append,Stream),
                    (train_2(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (train_3(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (train_4(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), ellipse(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), hexagon(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), rectangle(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), u_shaped(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), long(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), short(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), bucket(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), long(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), no_roof(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), flat_roof(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), peaked_roof(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), arc_roof(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), short(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), no_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), flat_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), peaked_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), circle_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), rectangle_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), triangle_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), arc_roof(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), circle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), circle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), circle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), rectangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), rectangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), rectangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), one_load(C), triangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), two_load(C), triangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C), three_load(C), triangle_load(C) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), ellipse(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), hexagon(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), rectangle(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), u_shaped(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), bucket(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), long(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), short(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), no_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), flat_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), peaked_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), arc_roof(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), circle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), rectangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), triangle_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), one_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), two_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), ellipse(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), hexagon(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), u_shaped(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), bucket(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), long(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), short(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), no_roof(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), flat_roof(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), peaked_roof(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), arc_roof(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), circle_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), rectangle_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), triangle_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), one_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), two_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A,B), three_load(A), three_load(B) -> write(Stream,"1, "); write(Stream,"0, ")),
                   nl(Stream),
                   close(Stream).


                   

has_car(T,C) :- member(C,T).

infront(T,C1,C2) :-
                 has_car(T,C1),
                 has_car(T,C2),
                 arg(1,C1,F),
                 arg(1,C2,G),
                 F + 1 =:= G.

ellipse(C) :- arg(2,C,ellipse).
hexagon(C) :- arg(2,C,hexagon).
rectangle(C) :- arg(2,C,rectangle).
u_shaped(C) :- arg(2,C,u_shaped).
bucket(C) :- arg(2,C,bucket).

long(C) :- arg(3,C,long).
short(C) :- arg(3,C,short).

no_roof(C) :- arg(4,C,none).
flat_roof(C) :- arg(4,C,flat).
peaked_roof(C) :- arg(4,C,peaked).
arc_roof(C) :- arg(4,C,arc).

circle_load(C) :- has_load0(C,circle).
rectangle_load(C) :- has_load0(C,rectangle).
triangle_load(C) :- has_load0(C,triangle).

one_load(C) :- has_load(C,1).
two_load(C) :- has_load(C,2).
three_load(C) :- has_load(C,3).

train_2(T) :- length(T,2).
train_3(T) :- length(T,3).
train_4(T) :- length(T,4).

has_load0(C,B) :- arg(5,C,D), arg(1,D,B).
has_load(C,B) :- arg(5,C,D), arg(2,D,B).

