% Author: Matthias Delfs
% Date: 07-Jul-17

:- use_module(library(lists)).

feature(T) :- arg(1,T,L), examine(L).

examine(([])).
examine((T)):-
                   open('trains_feature_csv_west.txt',append,Stream),
                    (train_2(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (train_3(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (train_4(T) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C1),ellipse(C1) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C2),hexagon(C2) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C3),rectangle(C3) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C4),u_shaped(C4) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C5),bucket(C5) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C6),long(C6) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C7),short(C7) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C8),no_roof(C8) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C9),flat_roof(C9) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C10),peaked_roof(C10) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C11),arc_roof(C11) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C12),circle_load(C12) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C13),rectangle_load(C13) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C14),triangle_load(C14) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C15),one_load(C15) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C16),two_load(C16) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C17),three_load(C17) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C18),long(C18), ellipse(C18) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C19),short(C19), ellipse(C19) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C20),no_roof(C20), ellipse(C20) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C21),flat_roof(C21), ellipse(C21) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C22),peaked_roof(C22), ellipse(C22) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C23),arc_roof(C23), ellipse(C23) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C24),circle_load(C24), ellipse(C24) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C25),rectangle_load(C25), ellipse(C25) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C26),triangle_load(C26), ellipse(C26) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C27),one_load(C27), ellipse(C27) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C28),two_load(C28), ellipse(C28) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C29),three_load(C29), ellipse(C29) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C30),long(C30), hexagon(C30) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C31),short(C31), hexagon(C31) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C32),no_roof(C32), hexagon(C32) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C33),flat_roof(C33), hexagon(C33) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C34),peaked_roof(C34), hexagon(C34) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C35),arc_roof(C35), hexagon(C35) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C36),circle_load(C36), hexagon(C36) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C37),rectangle_load(C37), hexagon(C37) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C38),triangle_load(C38), hexagon(C38) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C39),one_load(C39), hexagon(C39) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C40),two_load(C40), hexagon(C40) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C41),three_load(C41), hexagon(C41) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C42),long(C42), rectangle(C42) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C43),short(C43), rectangle(C43) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C44),no_roof(C44), rectangle(C44) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C45),flat_roof(C45), rectangle(C45) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C46),peaked_roof(C46), rectangle(C46) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C47),arc_roof(C47), rectangle(C47) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C48),circle_load(C48), rectangle(C48) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C49),rectangle_load(C49), rectangle(C49) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C50),triangle_load(C50), rectangle(C50) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C51),one_load(C51), rectangle(C51) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C52),two_load(C52), rectangle(C52) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C53),three_load(C53), rectangle(C53) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C54),long(C54), u_shaped(C54) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C55),short(C55), u_shaped(C55) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C56),no_roof(C56), u_shaped(C56) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C57),flat_roof(C57), u_shaped(C57) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C58),peaked_roof(C58), u_shaped(C58) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C59),arc_roof(C59), u_shaped(C59) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C60),circle_load(C60), u_shaped(C60) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C61),rectangle_load(C61), u_shaped(C61) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C62),triangle_load(C62), u_shaped(C62) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C63),one_load(C63), u_shaped(C63) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C64),two_load(C64), u_shaped(C64) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C65),three_load(C65), u_shaped(C65) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C66),long(C66), bucket(C66) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C67),short(C67), bucket(C67) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C68),no_roof(C68), bucket(C68) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C69),flat_roof(C69), bucket(C69) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C70),peaked_roof(C70), bucket(C70) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C71),arc_roof(C71), bucket(C71) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C72),circle_load(C72), bucket(C72) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C73),rectangle_load(C73), bucket(C73) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C74),triangle_load(C74), bucket(C74) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C75),one_load(C75), bucket(C75) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C76),two_load(C76), bucket(C76) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C77),three_load(C77), bucket(C77) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C78),no_roof(C78), long(C78) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C79),flat_roof(C79), long(C79) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C80),peaked_roof(C80), long(C80) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C81),arc_roof(C81), long(C81) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C82),circle_load(C82), long(C82) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C83),rectangle_load(C83), long(C83) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C84),triangle_load(C84), long(C84) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C85),one_load(C85), long(C85) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C86),two_load(C86), long(C86) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C87),three_load(C87), long(C87) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C88),no_roof(C88), short(C88) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C89),flat_roof(C89), short(C89) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C90),peaked_roof(C90), short(C90) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C91),arc_roof(C91), short(C91) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C92),circle_load(C92), short(C92) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C93),rectangle_load(C93), short(C93) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C94),triangle_load(C94), short(C94) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C95),one_load(C95), short(C95) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C96),two_load(C96), short(C96) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C97),three_load(C97), short(C97) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C98),circle_load(C98), no_roof(C98) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C99),rectangle_load(C99), no_roof(C99) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C100),triangle_load(C100), no_roof(C100) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C101),one_load(C101), no_roof(C101) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C102),two_load(C102), no_roof(C102) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C103),three_load(C103), no_roof(C103) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C104),circle_load(C104), flat_roof(C104) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C105),rectangle_load(C105), flat_roof(C105) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C106),triangle_load(C106), flat_roof(C106) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C107),one_load(C107), flat_roof(C107) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C108),two_load(C108), flat_roof(C108) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C109),three_load(C109), flat_roof(C109) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C110),circle_load(C110), peaked_roof(C110) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C111),rectangle_load(C111), peaked_roof(C111) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C112),triangle_load(C112), peaked_roof(C112) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C113),one_load(C113), peaked_roof(C113) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C114),two_load(C114), peaked_roof(C114) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C115),three_load(C115), peaked_roof(C115) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C116),circle_load(C116), arc_roof(C116) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C117),rectangle_load(C117), arc_roof(C117) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C118),triangle_load(C118), arc_roof(C118) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C119),one_load(C119), arc_roof(C119) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C120),two_load(C120), arc_roof(C120) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C121),three_load(C121), arc_roof(C121) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C122),one_load(C122), circle_load(C122) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C123),two_load(C123), circle_load(C123) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C124),three_load(C124), circle_load(C124) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C125),one_load(C125), rectangle_load(C125) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C126),two_load(C126), rectangle_load(C126) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C127),three_load(C127), rectangle_load(C127) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C128),one_load(C128), triangle_load(C128) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C129),two_load(C129), triangle_load(C129) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (has_car(T,C130),three_load(C130), triangle_load(C130) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A1,B1), ellipse(A1), ellipse(B1) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A2,B2), hexagon(A2), ellipse(B2) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A3,B3), rectangle(A3), ellipse(B3) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A4,B4), u_shaped(A4), ellipse(B4) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A5,B5), bucket(A5), ellipse(B5) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A6,B6), long(A6), ellipse(B6) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A7,B7), short(A7), ellipse(B7) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A8,B8), no_roof(A8), ellipse(B8) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A9,B9), flat_roof(A9), ellipse(B9) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A10,B10), peaked_roof(A10), ellipse(B10) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A11,B11), arc_roof(A11), ellipse(B11) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A12,B12), circle_load(A12), ellipse(B12) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A13,B13), rectangle_load(A13), ellipse(B13) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A14,B14), triangle_load(A14), ellipse(B14) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A15,B15), one_load(A15), ellipse(B15) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A16,B16), two_load(A16), ellipse(B16) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A17,B17), three_load(A17), ellipse(B17) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A18,B18), ellipse(A18), hexagon(B18) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A19,B19), hexagon(A19), hexagon(B19) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A20,B20), rectangle(A20), hexagon(B20) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A21,B21), u_shaped(A21), hexagon(B21) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A22,B22), bucket(A22), hexagon(B22) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A23,B23), long(A23), hexagon(B23) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A24,B24), short(A24), hexagon(B24) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A25,B25), no_roof(A25), hexagon(B25) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A26,B26), flat_roof(A26), hexagon(B26) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A27,B27), peaked_roof(A27), hexagon(B27) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A28,B28), arc_roof(A28), hexagon(B28) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A29,B29), circle_load(A29), hexagon(B29) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A30,B30), rectangle_load(A30), hexagon(B30) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A31,B31), triangle_load(A31), hexagon(B31) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A32,B32), one_load(A32), hexagon(B32) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A33,B33), two_load(A33), hexagon(B33) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A34,B34), three_load(A34), hexagon(B34) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A35,B35), ellipse(A35), rectangle(B35) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A36,B36), hexagon(A36), rectangle(B36) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A37,B37), rectangle(A37), rectangle(B37) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A38,B38), u_shaped(A38), rectangle(B38) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A39,B39), bucket(A39), rectangle(B39) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A40,B40), long(A40), rectangle(B40) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A41,B41), short(A41), rectangle(B41) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A42,B42), no_roof(A42), rectangle(B42) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A43,B43), flat_roof(A43), rectangle(B43) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A44,B44), peaked_roof(A44), rectangle(B44) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A45,B45), arc_roof(A45), rectangle(B45) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A46,B46), circle_load(A46), rectangle(B46) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A47,B47), rectangle_load(A47), rectangle(B47) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A48,B48), triangle_load(A48), rectangle(B48) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A49,B49), one_load(A49), rectangle(B49) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A50,B50), two_load(A50), rectangle(B50) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A51,B51), three_load(A51), rectangle(B51) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A52,B52), ellipse(A52), u_shaped(B52) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A53,B53), hexagon(A53), u_shaped(B53) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A54,B54), rectangle(A54), u_shaped(B54) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A55,B55), u_shaped(A55), u_shaped(B55) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A56,B56), bucket(A56), u_shaped(B56) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A57,B57), long(A57), u_shaped(B57) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A58,B58), short(A58), u_shaped(B58) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A59,B59), no_roof(A59), u_shaped(B59) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A60,B60), flat_roof(A60), u_shaped(B60) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A61,B61), peaked_roof(A61), u_shaped(B61) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A62,B62), arc_roof(A62), u_shaped(B62) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A63,B63), circle_load(A63), u_shaped(B63) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A64,B64), rectangle_load(A64), u_shaped(B64) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A65,B65), triangle_load(A65), u_shaped(B65) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A66,B66), one_load(A66), u_shaped(B66) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A67,B67), two_load(A67), u_shaped(B67) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A68,B68), three_load(A68), u_shaped(B68) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A69,B69), ellipse(A69), bucket(B69) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A70,B70), hexagon(A70), bucket(B70) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A71,B71), rectangle(A71), bucket(B71) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A72,B72), u_shaped(A72), bucket(B72) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A73,B73), bucket(A73), bucket(B73) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A74,B74), long(A74), bucket(B74) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A75,B75), short(A75), bucket(B75) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A76,B76), no_roof(A76), bucket(B76) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A77,B77), flat_roof(A77), bucket(B77) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A78,B78), peaked_roof(A78), bucket(B78) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A79,B79), arc_roof(A79), bucket(B79) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A80,B80), circle_load(A80), bucket(B80) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A81,B81), rectangle_load(A81), bucket(B81) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A82,B82), triangle_load(A82), bucket(B82) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A83,B83), one_load(A83), bucket(B83) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A84,B84), two_load(A84), bucket(B84) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A85,B85), three_load(A85), bucket(B85) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A86,B86), ellipse(A86), long(B86) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A87,B87), hexagon(A87), long(B87) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A88,B88), rectangle(A88), long(B88) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A89,B89), u_shaped(A89), long(B89) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A90,B90), bucket(A90), long(B90) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A91,B91), long(A91), long(B91) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A92,B92), short(A92), long(B92) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A93,B93), no_roof(A93), long(B93) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A94,B94), flat_roof(A94), long(B94) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A95,B95), peaked_roof(A95), long(B95) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A96,B96), arc_roof(A96), long(B96) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A97,B97), circle_load(A97), long(B97) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A98,B98), rectangle_load(A98), long(B98) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A99,B99), triangle_load(A99), long(B99) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A100,B100), one_load(A100), long(B100) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A101,B101), two_load(A101), long(B101) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A102,B102), three_load(A102), long(B102) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A103,B103), ellipse(A103), short(B103) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A104,B104), hexagon(A104), short(B104) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A105,B105), rectangle(A105), short(B105) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A106,B106), u_shaped(A106), short(B106) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A107,B107), bucket(A107), short(B107) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A108,B108), long(A108), short(B108) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A109,B109), short(A109), short(B109) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A110,B110), no_roof(A110), short(B110) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A111,B111), flat_roof(A111), short(B111) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A112,B112), peaked_roof(A112), short(B112) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A113,B113), arc_roof(A113), short(B113) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A114,B114), circle_load(A114), short(B114) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A115,B115), rectangle_load(A115), short(B115) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A116,B116), triangle_load(A116), short(B116) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A117,B117), one_load(A117), short(B117) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A118,B118), two_load(A118), short(B118) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A119,B119), three_load(A119), short(B119) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A120,B120), ellipse(A120), no_roof(B120) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A121,B121), hexagon(A121), no_roof(B121) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A122,B122), rectangle(A122), no_roof(B122) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A123,B123), u_shaped(A123), no_roof(B123) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A124,B124), bucket(A124), no_roof(B124) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A125,B125), long(A125), no_roof(B125) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A126,B126), short(A126), no_roof(B126) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A127,B127), no_roof(A127), no_roof(B127) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A128,B128), flat_roof(A128), no_roof(B128) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A129,B129), peaked_roof(A129), no_roof(B129) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A130,B130), arc_roof(A130), no_roof(B130) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A131,B131), circle_load(A131), no_roof(B131) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A132,B132), rectangle_load(A132), no_roof(B132) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A133,B133), triangle_load(A133), no_roof(B133) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A134,B134), one_load(A134), no_roof(B134) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A135,B135), two_load(A135), no_roof(B135) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A136,B136), three_load(A136), no_roof(B136) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A137,B137), ellipse(A137), flat_roof(B137) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A138,B138), hexagon(A138), flat_roof(B138) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A139,B139), rectangle(A139), flat_roof(B139) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A140,B140), u_shaped(A140), flat_roof(B140) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A141,B141), bucket(A141), flat_roof(B141) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A142,B142), long(A142), flat_roof(B142) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A143,B143), short(A143), flat_roof(B143) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A144,B144), no_roof(A144), flat_roof(B144) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A145,B145), flat_roof(A145), flat_roof(B145) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A146,B146), peaked_roof(A146), flat_roof(B146) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A147,B147), arc_roof(A147), flat_roof(B147) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A148,B148), circle_load(A148), flat_roof(B148) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A149,B149), rectangle_load(A149), flat_roof(B149) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A150,B150), triangle_load(A150), flat_roof(B150) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A151,B151), one_load(A151), flat_roof(B151) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A152,B152), two_load(A152), flat_roof(B152) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A153,B153), three_load(A153), flat_roof(B153) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A154,B154), ellipse(A154), peaked_roof(B154) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A155,B155), hexagon(A155), peaked_roof(B155) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A156,B156), rectangle(A156), peaked_roof(B156) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A157,B157), u_shaped(A157), peaked_roof(B157) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A158,B158), bucket(A158), peaked_roof(B158) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A159,B159), long(A159), peaked_roof(B159) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A160,B160), short(A160), peaked_roof(B160) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A161,B161), no_roof(A161), peaked_roof(B161) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A162,B162), flat_roof(A162), peaked_roof(B162) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A163,B163), peaked_roof(A163), peaked_roof(B163) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A164,B164), arc_roof(A164), peaked_roof(B164) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A165,B165), circle_load(A165), peaked_roof(B165) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A166,B166), rectangle_load(A166), peaked_roof(B166) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A167,B167), triangle_load(A167), peaked_roof(B167) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A168,B168), one_load(A168), peaked_roof(B168) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A169,B169), two_load(A169), peaked_roof(B169) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A170,B170), three_load(A170), peaked_roof(B170) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A171,B171), ellipse(A171), arc_roof(B171) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A172,B172), hexagon(A172), arc_roof(B172) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A173,B173), rectangle(A173), arc_roof(B173) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A174,B174), u_shaped(A174), arc_roof(B174) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A175,B175), bucket(A175), arc_roof(B175) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A176,B176), long(A176), arc_roof(B176) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A177,B177), short(A177), arc_roof(B177) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A178,B178), no_roof(A178), arc_roof(B178) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A179,B179), flat_roof(A179), arc_roof(B179) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A180,B180), peaked_roof(A180), arc_roof(B180) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A181,B181), arc_roof(A181), arc_roof(B181) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A182,B182), circle_load(A182), arc_roof(B182) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A183,B183), rectangle_load(A183), arc_roof(B183) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A184,B184), triangle_load(A184), arc_roof(B184) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A185,B185), one_load(A185), arc_roof(B185) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A186,B186), two_load(A186), arc_roof(B186) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A187,B187), three_load(A187), arc_roof(B187) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A188,B188), ellipse(A188), circle_load(B188) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A189,B189), hexagon(A189), circle_load(B189) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A190,B190), rectangle(A190), circle_load(B190) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A191,B191), u_shaped(A191), circle_load(B191) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A192,B192), bucket(A192), circle_load(B192) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A193,B193), long(A193), circle_load(B193) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A194,B194), short(A194), circle_load(B194) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A195,B195), no_roof(A195), circle_load(B195) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A196,B196), flat_roof(A196), circle_load(B196) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A197,B197), peaked_roof(A197), circle_load(B197) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A198,B198), arc_roof(A198), circle_load(B198) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A199,B199), circle_load(A199), circle_load(B199) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A200,B200), rectangle_load(A200), circle_load(B200) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A201,B201), triangle_load(A201), circle_load(B201) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A202,B202), one_load(A202), circle_load(B202) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A203,B203), two_load(A203), circle_load(B203) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A204,B204), three_load(A204), circle_load(B204) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A205,B205), ellipse(A205), rectangle_load(B205) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A206,B206), hexagon(A206), rectangle_load(B206) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A207,B207), rectangle(A207), rectangle_load(B207) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A208,B208), u_shaped(A208), rectangle_load(B208) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A209,B209), bucket(A209), rectangle_load(B209) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A210,B210), long(A210), rectangle_load(B210) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A211,B211), short(A211), rectangle_load(B211) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A212,B212), no_roof(A212), rectangle_load(B212) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A213,B213), flat_roof(A213), rectangle_load(B213) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A214,B214), peaked_roof(A214), rectangle_load(B214) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A215,B215), arc_roof(A215), rectangle_load(B215) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A216,B216), circle_load(A216), rectangle_load(B216) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A217,B217), rectangle_load(A217), rectangle_load(B217) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A218,B218), triangle_load(A218), rectangle_load(B218) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A219,B219), one_load(A219), rectangle_load(B219) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A220,B220), two_load(A220), rectangle_load(B220) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A221,B221), three_load(A221), rectangle_load(B221) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A222,B222), ellipse(A222), triangle_load(B222) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A223,B223), hexagon(A223), triangle_load(B223) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A224,B224), rectangle(A224), triangle_load(B224) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A225,B225), u_shaped(A225), triangle_load(B225) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A226,B226), bucket(A226), triangle_load(B226) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A227,B227), long(A227), triangle_load(B227) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A228,B228), short(A228), triangle_load(B228) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A229,B229), no_roof(A229), triangle_load(B229) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A230,B230), flat_roof(A230), triangle_load(B230) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A231,B231), peaked_roof(A231), triangle_load(B231) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A232,B232), arc_roof(A232), triangle_load(B232) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A233,B233), circle_load(A233), triangle_load(B233) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A234,B234), rectangle_load(A234), triangle_load(B234) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A235,B235), triangle_load(A235), triangle_load(B235) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A236,B236), one_load(A236), triangle_load(B236) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A237,B237), two_load(A237), triangle_load(B237) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A238,B238), three_load(A238), triangle_load(B238) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A239,B239), ellipse(A239), one_load(B239) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A240,B240), hexagon(A240), one_load(B240) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A241,B241), rectangle(A241), one_load(B241) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A242,B242), u_shaped(A242), one_load(B242) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A243,B243), bucket(A243), one_load(B243) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A244,B244), long(A244), one_load(B244) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A245,B245), short(A245), one_load(B245) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A246,B246), no_roof(A246), one_load(B246) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A247,B247), flat_roof(A247), one_load(B247) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A248,B248), peaked_roof(A248), one_load(B248) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A249,B249), arc_roof(A249), one_load(B249) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A250,B250), circle_load(A250), one_load(B250) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A251,B251), rectangle_load(A251), one_load(B251) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A252,B252), triangle_load(A252), one_load(B252) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A253,B253), one_load(A253), one_load(B253) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A254,B254), two_load(A254), one_load(B254) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A255,B255), three_load(A255), one_load(B255) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A256,B256), ellipse(A256), two_load(B256) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A257,B257), hexagon(A257), two_load(B257) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A258,B258), rectangle(A258), two_load(B258) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A259,B259), u_shaped(A259), two_load(B259) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A260,B260), bucket(A260), two_load(B260) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A261,B261), long(A261), two_load(B261) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A262,B262), short(A262), two_load(B262) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A263,B263), no_roof(A263), two_load(B263) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A264,B264), flat_roof(A264), two_load(B264) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A265,B265), peaked_roof(A265), two_load(B265) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A266,B266), arc_roof(A266), two_load(B266) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A267,B267), circle_load(A267), two_load(B267) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A268,B268), rectangle_load(A268), two_load(B268) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A269,B269), triangle_load(A269), two_load(B269) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A270,B270), one_load(A270), two_load(B270) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A271,B271), two_load(A271), two_load(B271) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A272,B272), three_load(A272), two_load(B272) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A273,B273), ellipse(A273), three_load(B273) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A274,B274), hexagon(A274), three_load(B274) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A275,B275), rectangle(A275), three_load(B275) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A276,B276), u_shaped(A276), three_load(B276) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A277,B277), bucket(A277), three_load(B277) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A278,B278), long(A278), three_load(B278) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A279,B279), short(A279), three_load(B279) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A280,B280), no_roof(A280), three_load(B280) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A281,B281), flat_roof(A281), three_load(B281) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A282,B282), peaked_roof(A282), three_load(B282) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A283,B283), arc_roof(A283), three_load(B283) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A284,B284), circle_load(A284), three_load(B284) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A285,B285), rectangle_load(A285), three_load(B285) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A286,B286), triangle_load(A286), three_load(B286) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A287,B287), one_load(A287), three_load(B287) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A288,B288), two_load(A288), three_load(B288) -> write(Stream,"1, "); write(Stream,"0, ")),
                    (infront(T,A289,B289), three_load(A289), three_load(B289) -> write(Stream,"1, "); write(Stream,"0, ")),
                   nl(Stream),
                   close(Stream).


                   

has_car(T,C) :- member(C,T).

infront(T,C1,C2) :-
                 has_car(T,C1),
                 has_car(T,C2),
                 arg(1,C1,F),
                 arg(1,C2,G),
                 F + 1 =:= G.

ellipse(C) :- arg(2,C,ellipse).
hexagon(C) :- arg(2,C,hexagon).
rectangle(C) :- arg(2,C,rectangle).
u_shaped(C) :- arg(2,C,u_shaped).
bucket(C) :- arg(2,C,bucket).

long(C) :- arg(3,C,long).
short(C) :- arg(3,C,short).

no_roof(C) :- arg(4,C,none).
flat_roof(C) :- arg(4,C,flat).
peaked_roof(C) :- arg(4,C,peaked).
arc_roof(C) :- arg(4,C,arc).

circle_load(C) :- has_load0(C,circle).
rectangle_load(C) :- has_load0(C,rectangle).
triangle_load(C) :- has_load0(C,triangle).

one_load(C) :- has_load(C,1).
two_load(C) :- has_load(C,2).
three_load(C) :- has_load(C,3).

train_2(T) :- length(T,2).
train_3(T) :- length(T,3).
train_4(T) :- length(T,4).

has_load0(C,B) :- arg(5,C,D), arg(1,D,B).
has_load(C,B) :- arg(5,C,D), arg(2,D,B).

